chore: updating dependabot to support gha, TS, JS and rust packages
rajpalc7/aries-askar pull request #1
Opened 2024-04-24 23:19 UTC by rajpalc7

2024-05-15 21:51 UTC, rajpalc7 commented
Hi @wadeBarnes, this is ready for review.

2024-05-16 14:44 UTC, WadeBarnes requested changes
@rajpalc7, You identified the JavaScript workspace structure correctly, but missed it with the `cargo` manifests.

2024-05-16 17:38 UTC, rajpalc7 commented
Hi @WadeBarnes , cargo manifests have been taken care of now.

2024-05-16 18:47 UTC, WadeBarnes approved these changes

2024-05-21 16:37 UTC, closed without merging